{% set name = "pytest-codeblocks" %}
{% set version = "0.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c41cb51c3f0e5caab516fa0e30cfd0dad82dc92fcd17a8c11d3399492fec52c2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - dataclasses
    - pytest

test:
  imports:
    - pytest_codeblocks
  requires:
    - pytest
  source_files:
    - README.md
    - tests
  commands:
    - python -m pytest

about:
  home: https://github.com/nschloe/pytest-codeblocks
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Test code blocks in your READMEs
  dev_url: https://github.com/nschloe/pytest-codeblocks

extra:
  recipe-maintainers:
    - nschloe
