{% set name = "pytest-codeblocks" %}
{% set version = "0.17.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 446e1babd182f54b4f113d567737a22f5405cade144c08a0085b2985247943d5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    - setuptools
  run:
    - python >=3
    - dataclasses
    - pytest

test:
  imports:
    - pytest_codeblocks
  requires:
    - pytest
  source_files:
    - README.md
    - tests
  commands:
    - python -m pytest -p pytester

about:
  home: https://github.com/nschloe/pytest-codeblocks
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Test code blocks in your READMEs
  dev_url: https://github.com/nschloe/pytest-codeblocks

extra:
  recipe-maintainers:
    - nschloe
